// collections
export const FETCH_COLLECTIONS_PENDING = 'FETCH_COLLECTIONS_PENDING';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

export const CREATE_COLLECTION_PENDING = 'CREATE_COLLECTION_PENDING';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILED = 'CREATE_COLLECTION_FAILED';

export const UPLOAD_COVER_IMAGE_PENDING = 'UPLOAD_COVER_IMAGE_PENDING';
export const UPLOAD_COVER_IMAGE_SUCCESS = 'UPLOAD_COVER_IMAGE_SUCCESS';
export const UPLOAD_COVER_IMAGE_FAILED = 'UPLOAD_COVER_IMAGE_FAILED';
