// collections
export const FETCH_COLLECTIONS_PENDING = 'FETCH_COLLECTIONS_PENDING';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

export const CREATE_COLLECTION_PENDING = 'CREATE_COLLECTION_PENDING';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILED = 'CREATE_COLLECTION_FAILED';
